# THIS SCRIPT AIMS TO COMPILE AND RUN PERFORMANCE BASED TESTS FOR CONVOLUTION.
# THE SCRIPT SHOULD ALSO OUTPUT RELEVANT PERFORMANCE METRICS

echo "Compiling performance code.."
g++ perf.cpp -o perfHost
nvcc perf.cu -o perfDevice

# HERE, ADD SOME SORT OF PERF METRIC, FOR NOW WE USE TIME CMD IN LINUX
echo "CPU BASED IMPLEMENTATION RUNTIME:"
time ./perfHost

echo "GPU  BASED IMPLEMENTATION RUNTIME:"
time ./perfDevice
